version: "3"
services:
#    web:
#        build: .
#        ports:
#            - "8000:80"
#        depends_on:
#            - db
  # db:
  #   image: "mcr.microsoft.com/mssql/server"
  #   ports:
  #     - 1433:1433
  #   environment:
  #       SA_PASSWORD: "P@xxw0rd"
  #       ACCEPT_EULA: "Y"
  #   volumes: 
  #     - db-storage:/var/opt/sql
  
  db-postgis:
    # image: postgis/postgis
    build: .
    ports:
      - 5433:5432
    environment: 
      POSTGRES_PASSWORD: "P@xxw0rd"
    volumes: 
      - ./geodata:/geodata
      - pg-data:/var/lib/postgresql/data
    container_name: spatialdb
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 80:80
    volumes: 
      - ./servers.json:/pgadmin4/servers.json
    environment: 
      PGADMIN_DEFAULT_EMAIL: "tluyo@wordstream.com"
      PGADMIN_DEFAULT_PASSWORD: "wordstream"

volumes: 
  # db-storage:
  pg-data:
