version: "3"
services:
  # db:
  #   image: "mcr.microsoft.com/mssql/server"
  #   ports:
  #     - 1433:1433
  #   environment:
  #       SA_PASSWORD: "pub"
  #       ACCEPT_EULA: "Y"
  #   volumes: 
  #     - db-storage:/var/opt/sql
  
  db-postgis:
    # image: postgis/postgis
    build: .
    ports:
      - 5433:5432
    environment: 
      POSTGRES_PASSWORD: "pub"
    volumes: 
      - ./geodata:/geodata
      - pg-data:/var/lib/postgresql/data
    container_name: spatialdb
    networks:
      - net-spatial
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: '80M'
        reservations:
          cpus: '0.05'
          memory: '40M'
  
  # pgadmin:
  #   image: dpage/pgadmin4
  #   ports:
  #     - 80:80
  #   volumes: 
  #     - ./servers.json:/pgadmin4/servers.json
  #     # - ./external:/var/lib/pgadmin/storage/user_mail.com/external
  #   environment: 
  #     PGADMIN_DEFAULT_EMAIL: "user@mail.com"
  #     PGADMIN_DEFAULT_PASSWORD: "pub"
  #   networks:
  #     - net-spatial

  dockerpython:
    image: dockerpython
    build:
      context: app/server/.
      dockerfile: Dockerfile
    volumes:
      - ./app/server/:/app
    ports:
      - 5000:5000
    networks:
      - net-spatial
    depends_on:
      - db-postgis
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: '80M'
        reservations:
          cpus: '0.05'
          memory: '40M'
  
  react:
    image: mapapp
    build:
      context: app/client/.
      dockerfile: Dockerfile
    volumes:
      - ./app/client/:/app
    ports:
      - 3000:5000

networks:
  net-spatial:

volumes: 
  # db-storage:
  pg-data:
