version: "3"
services:
  # db:
  #   image: "mcr.microsoft.com/mssql/server"
  #   ports:
  #     - 1433:1433
  #   environment:
  #       SA_PASSWORD: "pub"
  #       ACCEPT_EULA: "Y"
  #   volumes: 
  #     - db-storage:/var/opt/sql
  
  db-postgis:
    # image: postgis/postgis
    build: .
    ports:
      - 5433:5432
    environment: 
      POSTGRES_PASSWORD: "pub"
    volumes: 
      - ./geodata:/geodata
      - pg-data:/var/lib/postgresql/data
    container_name: spatialdb
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 80:80
    volumes: 
      - ./servers.json:/pgadmin4/servers.json
      # - ./external:/var/lib/pgadmin/storage/user_mail.com/external
    environment: 
      PGADMIN_DEFAULT_EMAIL: "user@mail.com"
      PGADMIN_DEFAULT_PASSWORD: "pub"

volumes: 
  # db-storage:
  pg-data:
