version: "3"
services:
  db-postgis:
    build:
      context: db/.
      dockerfile: Dockerfile
    image: mypostgis
    ports:
      - 5432:5432
    environment: 
      POSTGRES_PASSWORD: "pub"
    volumes: 
      - pg-data:/var/lib/postgresql/data
    container_name: spatialdb
    networks:
      - net-spatial
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: '80M'
        reservations:
          cpus: '0.05'
          memory: '40M'
  
  dockerpython:
    image: dockerpython
    build:
      context: app/server/.
      dockerfile: Dockerfile
    container_name: dockerpython
    volumes:
      - ./app/server/:/app
    ports:
      - 5000:5000
    networks:
      - net-spatial
    depends_on:
      - db-postgis
    deploy:
      resources:
        limits:
          cpus: '0.10'
          memory: '80M'
        reservations:
          cpus: '0.05'
          memory: '40M'
  
  react:
    image: mapapp
    build:
      context: app/client/.
      dockerfile: Dockerfile
    container_name: mapapp
    stdin_open: true
    volumes:
      - ./app/client/:/app
      - /app/node_modules
    ports:
      - 3000:3000
  
  client-vanillajs:
    image: vanillajs
    build: 
      context: app/client_vanillajs/.
      dockerfile: Dockerfile
    container_name: vanillajs
    ports:
      - 8088:80
    environment:
      - NGINX_PORT=80
    networks:
      - net-spatial
    depends_on:
      - dockerpython           
    

  # pgadmin:
  #   image: dpage/pgadmin4
  #   ports:
  #     - 80:80
  #   volumes: 
  #     - ./servers.json:/pgadmin4/servers.json
  #     # - ./external:/var/lib/pgadmin/storage/user_mail.com/external
  #   environment: 
  #     PGADMIN_DEFAULT_EMAIL: "user@mail.com"
  #     PGADMIN_DEFAULT_PASSWORD: "pub"
  #   networks:
  #     - net-spatial

networks:
  net-spatial:

volumes: 
  # db-storage:
  pg-data:
